# 07 Exercise - Basic Linear Algebra

This exercise set is all about doing standard linear algebra exercises using NumPy. 

In [1]:
#DON'T MODIFY THIS CELL, ONLY RUN IT.

# Importing NumPy as np.
import numpy as np

## Exercise 1: Import the Linalg Submodule

In [2]:
# Importing the linalg submodule from NumPy
from numpy import linalg

## Exercise 2: Simple Vector Operations

### Exercise 2a: 
Are any of the vectors $[1, 2, 3]$  and $[2, 3, 4]$  parallel? What about orthogonal?

In [10]:
# Make the vectors
v1 = np.array([1, 2, 3])
v2 = np.array([2, 3, 4])
# Checking if parallel
print('parallel?', np.dot(v1, v2) == (v1.size * v2.size))
# Checking if orthogonal
print('orthogonal?', np.dot(v1, v2) == 0)


parallel? False
orthogonal? False


### Exercise 2b: 
Can you find the angle between the vector $[1, 2, 3]$ and $[2, 3, 4]$?

In [12]:
# Defining the angle function
np.arccos(v1.dot(v2) / (linalg.norm(v1) * linalg.norm(v2)))
# Finding the angle


0.12186756768575456

## Exercise 3: Simple Matrix Operations

Define the matrices 
$$ A= 
\begin{bmatrix}
1&1&2\\
1&1&1\\
1&1&1
\end{bmatrix}\quad \text{and}\quad B= 
\begin{bmatrix}
1&0&0\\
0&1&-2\\
0&0&1
\end{bmatrix}.
$$

### Exercise 3a: 
Find the matrix product $AB$.

In [15]:
# Defining the matrices
a = np.array([[1,1,2],[1,1,1],[1,1,1]])
b = np.array([[1,0,0],[0,1,-2],[0,0,1]])
# Finding the matrix product AB
a @ b

array([[ 1,  1,  0],
       [ 1,  1, -1],
       [ 1,  1, -1]])

### Exercise 3b: 
Find the matrix product $B^{-1}A^5$.

In [17]:
# Find the matrix power
linalg.inv(b) @ a**5

array([[ 1.,  1., 32.],
       [ 3.,  3.,  3.],
       [ 1.,  1.,  1.]])

### Exercise 3c: 
Find the transpose of $A$, namely $A^T$. Compute the product $A A^T$.

In [19]:
# Finding the transpose of $A$
a.T
# Finding the product of $AA^T$
a @ a.T

array([[6, 4, 4],
       [4, 3, 3],
       [4, 3, 3]])

## Exercise 4: Balancing Chemical Equations

In this exercise we are going to use NumPy to balance a set of chemical equations. The question is how to balance the equation
$$x*C_4H_{10}+y*O_2 = v*H_2O + w*CO_2.$$
Written as vectors this becomes
$$x*[4,10,0]+y*[0,0,2]=z*[0,2,1] + w*[1,0,2],$$
or equivalently,
$$
\begin{bmatrix}
4&0&0\\
10&0&-2\\
0&2&-1
\end{bmatrix}
\begin{bmatrix}
x\\ y\\ z
\end{bmatrix} 
=w*\begin{bmatrix}
1\\ 0\\ 2
\end{bmatrix}.
$$

### Exercise 4a: 
Find out if the matrix is invertible.

In [29]:
# Checking if the matrix is invertible
m = np.array([[4,0,0],[10,0,-2],[0,2,-1]])
linalg.det(m)

16.000000000000007

### Exercise 4b: 
Solve the linear system with $w=1$.

In [32]:
# Finding a solution
result = linalg.solve(m, np.array([1, 0, 2]))

### Exercise 4c: 
Having 0.25 of a carbon atom doesn’t really make sense. Multiply the vector with the whole numbers from 1 to 10 to see when the solution consists of only whole numbers.

In [33]:
# Print out the multiples from 1 to 10
for i in range(1, 11):
    print(i*result)

[0.25  1.625 1.25 ]
[0.5  3.25 2.5 ]
[0.75  4.875 3.75 ]
[1.  6.5 5. ]
[1.25  8.125 6.25 ]
[1.5  9.75 7.5 ]
[ 1.75  11.375  8.75 ]
[ 2. 13. 10.]
[ 2.25  14.625 11.25 ]
[ 2.5  16.25 12.5 ]


### Exercise 4d: 
Write up the balanced equation, in other words, what is $x,$ $y,$ $z,$ and $w$?

## Moral of the Story

NumPy's linear algebra module makes working with linear algebra easy. In many universities around the world, NumPy is used in courses for linear algebra. In Exercise 4 above, you saw that one can use NumPy to balance chemical equations. Many other applications of linear algebra exist and you can check out the article: https://medium.com/@jeremyjkun/here-s-just-a-fraction-of-what-you-can-do-with-linear-algebra-633383d4153f for more examples!